# Set the base image
FROM ubuntu
# Dockerfile author / maintainer 
MAINTAINER lvc0107 lvc0107@protonmail.com 

RUN apt-get update
RUN yes | apt-get install tmux
RUN yes| apt-get install virtualenvwrapper 
RUN apt-get install htop 
RUN yes | apt-get install ipython

CMD echo "hello world"

